version: "3"

services:
  web1:
    build:
      context: ./Python1
    expose:
      - 4000
  web2:
    build:
      context: ./Python2
    expose:
      - 4000
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy_lb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy_lb/certs:/etc/nginx/certs:ro
    depends_on:
      - web1
      - web2
